### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [Invisi/exif_importer#1]
The plugin is apparently very similar to an existing one since long (photo2shape). Please explain why a new one is needed, instead of help improving the existing one.
Rationale: we have hundreds of plugins, and it is getting increasingly difficult for users to find the right one. We are trying hard to reduce duplication and confusion.
Thanks.

**Comment by Invisi** [comment]
Hi there,
first of all sorry for the late reply, I forgot I had email notifications turned off.

exif_importer was written as an introduction to the QGIS world and I didn't know of photo2shape until after I was already done. They're both pretty similar, but do differ at certain points, so it should be possible to update the description to highlight the differences.
I can see why it'd be better for QGIS to just keep photo2shape and add new capabilities, however it would require me to rewrite large parts of photo2shape to keep it DRY.
Anyway, if you decide not to include it, I'll probably just add an (opt-in) update checker.

**Comment by pcav** [comment]
Please discuss with the authors of Photo2shape @alexbruy (better through the public qgis-dev list) to find the best course of action. In general, having many similar plugin is bad for everyone. Merging the two may have an higher initial cost, but will make maintenance and improvement  far smoother.

**Comment by pcav** [comment]
I do not see an improvement here: why closing this ticket?
Thanks.

**Comment by Invisi** [comment]
Hey,
I thought it as resolved since I was planning on contacting alexbruy about merging the two plugins as soon as I have the time to.

**Comment by pcav** [comment]
Great thing, thanks.
